version: '2'
services:
  neo4j: 
      image: neo4j:latest
      container_name: neo4j
      volumes:
          - /home/pkmlp/neo4j/data:/data/dbms
      ports: 
          - "7474:7474" 
          - "7687:7687" 
      environment: 
          NEO4J_AUTH: "none"
